# first stage
FROM golang:1.16-stretch as builder
WORKDIR /src
COPY go.mod .
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -tags netgo -o /bin/app -ldflags "-w -s"

# final stage
FROM debian:11-slim
WORKDIR /bin
COPY --from=builder --chown=1001 /bin/app .
EXPOSE 9090
USER 1001
ENTRYPOINT ["/bin/app"]
