apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  labels:
    app: argocd
    domain: gitops
    group: apps
    feature: namespaces
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: in-cluster
  source:
    repoURL: https://github.com/marcojarjour/workshop-tage-2021
    targetRevision: main
    path: infrastructure/20_namespaces
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
