
# APP-OF-APPS

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing
  namespace: argocd
  labels:
    app: argocd
    domain: gitops
    group: app-of-apps
    feature: tracing
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: in-cluster
  source:
    repoURL: https://github.com/marcojarjour/workshop-tage-2021
    targetRevision: main
    path: infrastructure/100_gitops/4_tracing
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
