apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  labels:
    feature: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: in-cluster
  source:
    repoURL: https://github.com/bygui86/workshop-tage-2021
    targetRevision: main
    path: infrastructure/70_databases/postgresql
  destination:
    name: in-cluster
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=background
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
