apiVersion: v1
kind: ConfigMap
metadata:
  name: http-client
data:
  # logging
  LOG_ENCODING: json

  # monitoring
  # ENABLE_MONITORING: "false"
  ENABLE_CUSTOM_METRICS: "true"

  # tracing
  # ENABLE_TRACING: "false"
  JAEGER_SERVICE_NAME: http-client
  JAEGER_SAMPLER_TYPE: const
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_REPORTER_FLUSH_INTERVAL: 1s
  JAEGER_AGENT_PORT: "6831"
  JAEGER_AGENT_HOST: jaeger-agent.tracing.svc.cluster.local
  JAEGER_REPORTER_LOG_SPANS: "true"

  # server
  REST_SERVER_HOST: http-server.apps.svc.cluster.local
  REST_SERVER_PORT: "8080"
