{
 "title": "PostgreSQL",
 "description": "PostgreSQL dashboard for metrics exported by Prometheus",
 "tags": [
  "databases",
  "postgresql"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "host", "label": "Host:", "query": { "query": "label_values(pg_up,job)" } },
   {
    "name": "db",
    "label": "DB:",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{job=~\"$host\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "interval",
    "label": "Interval:",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage (sec)",
   "type": "graph",
   "description": "User and system CPU time spent in seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"$host\"}[$interval])",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$host\"}",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$host\"}",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$host\"}",
     "legendFormat": "Open file desc"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 10 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$host\"} * 1000"
    }
   ]
  },
  {
   "title": "Total transactions",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 10 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=~\"$db\",job=~\"$host\"}[$interval])) + sum(irate(pg_stat_database_xact_rollback{datname=~\"$db\",job=~\"$host\"}[$interval]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{datname=~\"$db\",job=\"$host\"}[$interval]))",
     "legendFormat": "commits"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{datname=~\"$db\",job=\"$host\"}[$interval]))",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Longest transactions",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum(pg_stat_activity_max_tx_duration{job=\"$host\",datname=~\"$db\"}))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "xact_commit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_max_tx_duration{job=\"$host\",datname=~\"$db\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total connections",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 29 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{datname=~\"$db\",job=\"$host\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 3, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (state) (pg_stat_activity_count{datname=~\"$db\",job=\"$host\"})",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "Locks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (pg_locks_count{job=\"$host\",datname=~\"$db\"})",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Rows",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_fetched{datname=~\"$db\",job=~\"$host\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "select (fetched)",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_returned{datname=~\"$db\",job=~\"$host\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "select (returned)",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_inserted{datname=~\"$db\",job=~\"$host\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "insert",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_updated{datname=~\"$db\",job=~\"$host\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "update",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_deleted{datname=~\"$db\",job=~\"$host\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "delete",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Cache hit ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(pg_stat_database_blks_hit{datname=~\"$db\",job=\"$host\"}) / (sum(pg_stat_database_blks_hit{datname=~\"$db\",job=\"$host\"}) + sum(pg_stat_database_blks_read{datname=~\"$db\",job=\"$host\"}))",
       "legendFormat": "cache hit rate"
      }
     ]
    },
    {
     "title": "Deadlocks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "conflicts",
       "expr": "sum(rate(pg_stat_database_deadlocks{datname=~\"$db\",job=\"$host\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "deadlocks",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "conflicts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Conflicts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pg_stat_database_conflicts{datname=~\"$db\",job=\"$host\"}[$interval]))",
       "legendFormat": "conflicts"
      },
      {
       "expr": "sum(rate(pg_stat_database_conflicts_confl_bufferpin{datname=~\"$db\",job=\"$host\"}[$interval]))",
       "legendFormat": "bufferpin"
      },
      {
       "expr": "sum(rate(pg_stat_database_conflicts_confl_deadlock{datname=~\"$db\",job=\"$host\"}[$interval]))",
       "legendFormat": "deadlock"
      },
      {
       "expr": "sum(rate(pg_stat_database_conflicts_confl_lock{datname=~\"$db\",job=\"$host\"}[$interval]))",
       "legendFormat": "lock"
      },
      {
       "expr": "sum(rate(pg_stat_database_conflicts_confl_snapshot{datname=~\"$db\",job=\"$host\"}[$interval]))",
       "legendFormat": "snapshot"
      },
      {
       "expr": "sum(rate(pg_stat_database_conflicts_confl_tablespace{datname=~\"$db\",job=\"$host\"}[$interval]))",
       "legendFormat": "tablespace"
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sequential page cost",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_seq_page_cost{job=\"$host\"}"
      }
     ]
    },
    {
     "title": "Temp bytes",
     "type": "graph",
     "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
     "gridPos": { "h": 10, "w": 22, "x": 2, "y": 30 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_temp_bytes{job=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[$interval])",
       "legendFormat": "Temp bytes"
      }
     ]
    },
    {
     "title": "Random page cost",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 35 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_random_page_cost{job=\"$host\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_server_version_num{job=\"$host\"}"
      }
     ]
    },
    {
     "title": "Max connections",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 31 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_connections{job=\"$host\"}"
      }
     ]
    },
    {
     "title": "Max WAL size",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 31 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_wal_size_bytes{job=\"$host\"}"
      }
     ]
    },
    {
     "title": "Work memory",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 31 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_work_mem_bytes{job=\"$host\"}"
      }
     ]
    },
    {
     "title": "Maintenance work mem",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 31 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_maintenance_work_mem_bytes{job=\"$host\"}"
      }
     ]
    },
    {
     "title": "Shared buffers",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 35 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{job=\"$host\"}"
      }
     ]
    },
    {
     "title": "Effective cache",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 35 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_effective_cache_size_bytes{job=\"$host\"}"
      }
     ]
    },
    {
     "title": "Max worker processes",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 35 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_worker_processes{job=\"$host\"}"
      }
     ]
    },
    {
     "title": "Max parallel workers",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 35 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_parallel_workers{job=\"$host\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replica",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{job=\"$host\"}"
      }
     ]
    },
    {
     "title": "Replication Lag",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 4, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg_replication_lag{datname=~\"$db\",job=\"$host\"}"
      }
     ]
    }
   ]
  }
 ]
}