{
 "title": "Loki - Chunks",
 "tags": [
  "logging",
  "loki"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_container_info{container=~\".*loki.*\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Active Series / Chunks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_chunks)",
     "legendFormat": "series"
    }
   ]
  },
  {
   "title": "Chunks per series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_chunks) / sum(loki_ingester_memory_streams)",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Chunk Duration hours (end-start)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(loki_ingester_chunk_bounds_hours_bucket[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_bounds_hours_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(rate(loki_ingester_chunk_bounds_hours_sum[5m])) / sum(rate(loki_ingester_chunk_bounds_hours_count[5m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Flush Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_utilization_bucket[$__interval])) by (le)) * 1",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_utilization_bucket[$__interval])) by (le)) * 1",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "sum(rate(loki_ingester_chunk_utilization_sum[$__interval])) * 1 / sum(rate(loki_ingester_chunk_utilization_count[$__interval]))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Age",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_age_seconds_bucket[$__interval])) by (le)) * 1e3",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_age_seconds_bucket[$__interval])) by (le)) * 1e3",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "sum(rate(loki_ingester_chunk_age_seconds_sum[$__interval])) * 1e3 / sum(rate(loki_ingester_chunk_age_seconds_count[$__interval]))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(loki_ingester_chunk_entries_bucket[$__interval])) by (le)) * 1",
       "legendFormat": "99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(loki_ingester_chunk_entries_bucket[$__interval])) by (le)) * 1",
       "legendFormat": "50th Percentile"
      },
      {
       "expr": "sum(rate(loki_ingester_chunk_entries_sum[$__interval])) * 1 / sum(rate(loki_ingester_chunk_entries_count[$__interval]))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Entries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_chunk_store_index_entries_per_chunk_sum[5m])) / sum(rate(cortex_chunk_store_index_entries_per_chunk_count[5m]))",
       "legendFormat": "entries"
      }
     ]
    },
    {
     "title": "Queue Length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cortex_ingester_flush_queue_length",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Flush Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (label_replace(label_replace(rate(loki_ingester_chunk_age_seconds_count[$__interval]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"), \"status\", \"${1}\",   \"status_code\", \"([a-z]+)\"))",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  }
 ]
}