{
 "title": "Custom apps",
 "tags": [
  "apps",
  "services"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Standalone app",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ops",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ops_total{app=\"standalone\"}[1m])",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ops",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ops_total{app=\"grpc-client\"}[1m])",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Ops",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ops_total{app=\"grpc-server\"}[1m])",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Greetings",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(greetings_total{app=\"grpc-client\"}[1m]))",
       "legendFormat": "grpc-client"
      }
     ]
    },
    {
     "title": "Greetings",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(greetings_total{app=\"grpc-server\"}[1m]))",
       "legendFormat": "grpc-server"
      }
     ]
    },
    {
     "title": "Greetings by name",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(greetings_total{app=\"grpc-client\"}[1m])",
       "legendFormat": "{{app}} / {{name}}"
      }
     ]
    },
    {
     "title": "Greetings by name",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(greetings_total{app=\"grpc-server\"}[1m])",
       "legendFormat": "{{app}} / {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ops",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ops_total{app=\"http-client\"}[1m])",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Ops",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ops_total{app=\"http-server\"}[1m])",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Requests by method",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(http_requests_total{app=\"http-client\"}[1m])",
       "legendFormat": "{{app}} / {{method}}"
      }
     ]
    },
    {
     "title": "Requests by method",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(http_requests_total{app=\"http-server\"}[1m])",
       "legendFormat": "{{app}} / {{method}}"
      }
     ]
    },
    {
     "title": "[http-client / getProducts] Histogram over time",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "http_requests_execution_time_milliseconds_bucket{app=\"http-client\",method=\"getProducts\"}"
      }
     ]
    },
    {
     "title": "[http-server / getProducts] Histogram over time",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "http_requests_execution_time_milliseconds_bucket{app=\"http-server\",method=\"getProducts\"}"
      }
     ]
    },
    {
     "title": "[http-client / getProducts] Histogram",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_requests_execution_time_milliseconds_bucket{app=\"http-client\",method=\"getProducts\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "[http-server / getProducts] Histogram",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_requests_execution_time_milliseconds_bucket{app=\"http-server\",method=\"getProducts\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Broker apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ops",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ops_total{app=\"kafka-producer\"}[1m])",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Ops",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(ops_total{app=\"kafka-consumer\"}[1m])",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Messages",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(success_published_messages_total{app=\"kafka-producer\"}[1m])",
       "legendFormat": "{{app}} / {{topic}} / success"
      },
      {
       "expr": "rate(fail_published_messages_total{app=\"kafka-producer\"}[1m])",
       "legendFormat": "{{app}} / {{topic}} / fail"
      }
     ]
    },
    {
     "title": "Messages",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(success_consumed_messages_total{app=\"kafka-consumer\"}[1m])",
       "legendFormat": "{{app}} / {{topic}} / success"
      },
      {
       "expr": "rate(fail_consumed_messages_total{app=\"kafka-consumer\"}[1m])",
       "legendFormat": "{{app}} / {{topic}} / fail"
      }
     ]
    },
    {
     "title": "Tracing injection",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(failed_tracing_injection_total{app=\"kafka-producer\"}[1m])",
       "legendFormat": "{{app}} / {{topic}} / fail"
      }
     ]
    },
    {
     "title": "Consume errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(consumer_errors_total{app=\"kafka-consumer\"}[1m])",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  }
 ]
}