{
 "title": "Global status",
 "tags": [
  "services",
  "kubernetes"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace:",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 18, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{namespace!=\"\", pod!=\"\"}",
     "legendFormat": "{{ namespace }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)"
    }
   ]
  },
  {
   "title": "MEM requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores)"
    }
   ]
  },
  {
   "title": "MEM limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes)"
    }
   ]
  },
  {
   "title": "CPU available",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "MEM limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes)"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total > 0",
     "legendFormat": "{{ pod }} - {{ container }}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) * 100 / sum(kube_pod_container_resource_limits_cpu_cores)",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) * 100 / sum(kube_pod_container_resource_limits_memory_bytes)",
     "legendFormat": "MEM"
    }
   ]
  },
  {
   "title": "Requested",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) * 100 / sum(kube_node_status_allocatable_cpu_cores)",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) * 100 / sum(kube_node_status_allocatable_memory_bytes)",
     "legendFormat": "MEM"
    }
   ]
  },
  {
   "title": "Global situation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sum(kube_node_labels)", "legendFormat": "total" }
     ]
    },
    {
     "title": "Namespaces",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sum(kube_namespace_labels)", "legendFormat": "total" }
     ]
    },
    {
     "title": "Services",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sum(kube_service_labels)", "legendFormat": "total" }
     ]
    },
    {
     "title": "Deployments",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sum(kube_deployment_labels)", "legendFormat": "total" }
     ]
    },
    {
     "title": "StatefulSets",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sum(kube_statefulset_labels)", "legendFormat": "total" }
     ]
    },
    {
     "title": "DaemonSets",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sum(kube_daemonset_labels)", "legendFormat": "total" }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sum(kube_pod_info)", "legendFormat": "total" }
     ]
    },
    {
     "title": "Containers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sum(kube_pod_container_info)", "legendFormat": "total" }
     ]
    },
    {
     "title": "ConfigMaps",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sum(kube_configmap_info)", "legendFormat": "total" }
     ]
    },
    {
     "title": "Secrets",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sum(kube_secret_labels)", "legendFormat": "total" }
     ]
    },
    {
     "title": "PersistentVolumeClaims",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_labels)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "PersistentVolumes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolume_labels)",
       "legendFormat": "total"
      }
     ]
    },
    {
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "format": "short",
     "valueName": "current",
     "targets": [
      { "expr": "sum(kube_deployment_labels)", "legendFormat": "deployments" },
      { "expr": "sum(kube_statefulset_labels)", "legendFormat": "statefulsets" },
      { "expr": "sum(kube_daemonset_labels)", "legendFormat": "daemonsets" }
     ]
    },
    {
     "title": "Deployments",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_unavailable > bool 0",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Statefulsets",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready != bool kube_statefulset_status_replicas",
       "legendFormat": "{{ statefulset }}"
      }
     ]
    },
    {
     "title": "Daemonsets",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "kube_daemonset_status_number_unavailable > bool 0",
       "legendFormat": "{{ daemonset }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace $namespace situation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "namespace",
   "collapsed": true,
   "panels": [
    {
     "title": "Deployments",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_labels{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "StatefulSets",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_statefulset_labels{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "DaemonSets",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_daemonset_labels{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Deployments",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\"}",
       "legendFormat": "target"
      },
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\"}",
       "legendFormat": "available"
      },
      {
       "expr": "kube_deployment_status_replicas_unavailable{namespace=\"$namespace\"}",
       "legendFormat": "unavailable"
      },
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\"} * 100 / kube_deployment_status_replicas{namespace=\"$namespace\"}",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_info{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Containers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_info{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "PersistentVolumeClaims",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_labels{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Up/Down services",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "up{namespace=\"$namespace\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Statefulsets",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas{namespace=\"$namespace\"}",
       "legendFormat": "target"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\"}",
       "legendFormat": "ready"
      },
      {
       "expr": "kube_statefulset_status_replicas{namespace=\"$namespace\"} - kube_statefulset_status_replicas_ready{namespace=\"$namespace\"}",
       "legendFormat": "unavailable"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\"} * 100 / kube_statefulset_status_replicas{namespace=\"$namespace\"}",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "Daemonsets",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "kube_daemonset_status_desired_number_scheduled{namespace=\"$namespace\"}",
       "legendFormat": "target"
      },
      {
       "expr": "kube_daemonset_status_number_ready{namespace=\"$namespace\"}",
       "legendFormat": "ready"
      },
      {
       "expr": "kube_daemonset_status_number_unavailable{namespace=\"$namespace\"}",
       "legendFormat": "unavailable"
      },
      {
       "expr": "kube_daemonset_status_number_ready{namespace=\"$namespace\"} * 100 / kube_daemonset_status_desired_number_scheduled{namespace=\"$namespace\"}",
       "legendFormat": "percentage"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace $namespace situation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployments",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_labels{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "StatefulSets",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_statefulset_labels{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "DaemonSets",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_daemonset_labels{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Deployments",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=\"$namespace\"}",
       "legendFormat": "target"
      },
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\"}",
       "legendFormat": "available"
      },
      {
       "expr": "kube_deployment_status_replicas_unavailable{namespace=\"$namespace\"}",
       "legendFormat": "unavailable"
      },
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\"} * 100 / kube_deployment_status_replicas{namespace=\"$namespace\"}",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_info{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Containers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_info{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "PersistentVolumeClaims",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_labels{namespace=\"$namespace\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Up/Down services",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "up{namespace=\"$namespace\"}",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Statefulsets",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas{namespace=\"$namespace\"}",
       "legendFormat": "target"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\"}",
       "legendFormat": "ready"
      },
      {
       "expr": "kube_statefulset_status_replicas{namespace=\"$namespace\"} - kube_statefulset_status_replicas_ready{namespace=\"$namespace\"}",
       "legendFormat": "unavailable"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\"} * 100 / kube_statefulset_status_replicas{namespace=\"$namespace\"}",
       "legendFormat": "percentage"
      }
     ]
    },
    {
     "title": "Daemonsets",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "kube_daemonset_status_desired_number_scheduled{namespace=\"$namespace\"}",
       "legendFormat": "target"
      },
      {
       "expr": "kube_daemonset_status_number_ready{namespace=\"$namespace\"}",
       "legendFormat": "ready"
      },
      {
       "expr": "kube_daemonset_status_number_unavailable{namespace=\"$namespace\"}",
       "legendFormat": "unavailable"
      },
      {
       "expr": "kube_daemonset_status_number_ready{namespace=\"$namespace\"} * 100 / kube_daemonset_status_desired_number_scheduled{namespace=\"$namespace\"}",
       "legendFormat": "percentage"
      }
     ]
    }
   ]
  }
 ]
}