{
 "title": "Go services",
 "description": "Dashboard to commonly monitor services written in Golang",
 "tags": [
  "go",
  "services"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace:",
    "query": "label_values(go_memstats_alloc_bytes,namespace)"
   },
   {
    "name": "job",
    "label": "Service:",
    "query": "label_values(go_memstats_alloc_bytes{namespace=\"$namespace\"},job)"
   },
   {
    "name": "pod",
    "label": "Pod:",
    "query": "label_values(go_memstats_alloc_bytes{job=\"$job\"},pod)"
   },
   { "name": "interval", "label": "Interval:", "query": "1m,5m,10m,30m,1h,3h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "go_threads{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "threads"
    },
    {
     "expr": "go_goroutines{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "goroutines"
    },
    {
     "expr": "(process_resident_memory_bytes{job=\"$job\",pod=\"$pod\"} / process_virtual_memory_bytes{job=\"$job\",pod=\"$pod\"} ) * 100",
     "legendFormat": "memory"
    },
    {
     "expr": "process_open_fds{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "open file desc"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "next GC target"
    }
   ]
  },
  {
   "title": "Total memory from OS",
   "type": "graph",
   "description": "A metric to measure how many bytes of memory in total is taken from system by Go.\nIt sums all the sys metrics described below.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "total from os"
    }
   ]
  },
  {
   "title": "Memory consume rate",
   "type": "graph",
   "description": "This metric increases as objects are allocated in the Heap, but doesn’t decrease when they are freed.\nIt is useful as doing rate() on it shows how many bytes/s of memory app consumes.\nIt is also \"durable\" across restarts and scrape misses.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\",pod=\"$pod\"}[$interval])",
     "legendFormat": "consume rate"
    }
   ]
  },
  {
   "title": "Go-threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Go-routines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "total from os"
    }
   ]
  },
  {
   "title": "Unix memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unix memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\",pod=\"$pod\"}",
       "legendFormat": "used"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"$job\",pod=\"$pod\"}",
       "legendFormat": "total (ram + swap)"
      }
     ]
    },
    {
     "title": "Unix memory used stats",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{job=\"$job\",pod=\"$pod\"}[$interval])",
       "legendFormat": "used rate ($interval)"
      },
      {
       "expr": "deriv(process_resident_memory_bytes{job=\"$job\",pod=\"$pod\"}[$interval])",
       "legendFormat": "used deriv ($interval)"
      }
     ]
    },
    {
     "title": "Unix memory total stats",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(process_virtual_memory_bytes{job=\"$job\",pod=\"$pod\"}[$interval])",
       "legendFormat": "total rate ($interval)"
      },
      {
       "expr": "deriv(process_virtual_memory_bytes{job=\"$job\",pod=\"$pod\"}[$interval])",
       "legendFormat": "total deriv ($interval)"
      }
     ]
    }
   ]
  },
  {
   "title": "Golang memory overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Golang memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\",pod=\"$pod\"} + go_memstats_heap_inuse_bytes{job=\"$job\",pod=\"$pod\"}",
       "legendFormat": "in use"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\",pod=\"$pod\"}",
       "legendFormat": "idle"
      }
     ]
    },
    {
     "title": "Golang memory in use stats",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_stack_inuse_bytes{job=\"$job\",pod=\"$pod\"}[$interval]) + rate(go_memstats_heap_inuse_bytes{job=\"$job\",pod=\"$pod\"}[$interval])",
       "legendFormat": "in use rate ($interval)"
      },
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{job=\"$job\",pod=\"$pod\"}[$interval]) + deriv(go_memstats_heap_inuse_bytes{job=\"$job\",pod=\"$pod\"}[$interval])",
       "legendFormat": "in use deriv ($interval)"
      }
     ]
    },
    {
     "title": "Golang memory idle stats",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_heap_idle_bytes{job=\"$job\",pod=\"$pod\"}[$interval])",
       "legendFormat": "idle rate ($interval)"
      },
      {
       "expr": "deriv(go_memstats_heap_idle_bytes{job=\"$job\",pod=\"$pod\"}[$interval])",
       "legendFormat": "idle deriv ($interval)"
      }
     ]
    }
   ]
  },
  {
   "title": "Heap memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap total size",
     "type": "graph",
     "description": "A metric which shows how much bytes of memory is allocated on the Heap for the Objects. The value is same as go_memstats_alloc_bytes.\nThis metric counts all reachable heap objects plus unreachable objects, GC has not yet freed.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$job\",pod=\"$pod\"}",
       "legendFormat": "total size"
      }
     ]
    },
    {
     "title": "Heap allocated but unused",
     "type": "graph",
     "description": "A metric to show how many bytes of memory has been allocated for the heap, but currently unused.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\",pod=\"$pod\"} - go_memstats_heap_alloc_bytes{job=\"$job\",pod=\"$pod\"}",
       "legendFormat": "unused"
      }
     ]
    },
    {
     "title": "Heap reserved but releasable",
     "type": "graph",
     "description": "A metric to estimate how many bytes of memory could be released, but is kept by runtime, so that runtime can allocate objects on the heap without asking OS for more memory.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\",pod=\"$pod\"} - go_memstats_heap_released_bytes{job=\"$job\",pod=\"$pod\"}",
       "legendFormat": "reserved"
      }
     ]
    },
    {
     "title": "Heap allocated objects",
     "type": "graph",
     "description": "Allocated objects still alive",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"$job\",pod=\"$pod\"} - go_memstats_frees_total{job=\"$job\",pod=\"$pod\"}",
       "legendFormat": "objects"
      }
     ]
    },
    {
     "title": "Heap allocated objects rate",
     "type": "graph",
     "description": "Objects allocation rate",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"$job\",pod=\"$pod\"}[$interval])",
       "legendFormat": "rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Stack memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stack in use",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\",pod=\"$pod\"}",
       "legendFormat": "in use"
      }
     ]
    },
    {
     "title": "Stack obtained from os",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_sys_bytes{job=\"$job\",pod=\"$pod\"}",
       "legendFormat": "obtained from os"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC duration",
     "type": "stat",
     "description": "Return the minimum GC pause times",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\",pod=\"$pod\",quantile=\"0\"}",
       "legendFormat": "quantiles = 0"
      },
      {
       "expr": "go_gc_duration_seconds{job=\"$job\",pod=\"$pod\",quantile=\"0.25\"}",
       "legendFormat": "quantiles = 0.25"
      },
      {
       "expr": "go_gc_duration_seconds{job=\"$job\",pod=\"$pod\",quantile=\"0.25\"}",
       "legendFormat": "quantiles = 0.5"
      },
      {
       "expr": "go_gc_duration_seconds{job=\"$job\",pod=\"$pod\",quantile=\"0.25\"}",
       "legendFormat": "quantiles = 0.75"
      },
      {
       "expr": "go_gc_duration_seconds{job=\"$job\",pod=\"$pod\",quantile=\"1\"}",
       "legendFormat": "quantiles = 1"
      }
     ]
    }
   ]
  }
 ]
}