apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - 1_standalone.yaml
  - 2_grpc.yaml
  - 3_http.yaml
  - 4_broker.yaml

commonLabels:
  domain: apps
  group: apps
